config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', :omniauth_callbacks => 'users/omniauth_callbacks'  }
  get '/about' => 'static#about'

  post '/recipe_ingredients' => 'recipeingredients#amount'

  get '/search' => 'recipes#search'
  post '/search' => 'recipes#results'

  resources :ingredients
  resources :recipes do
    resources :comments
    resources :recipe_ingredients, only: [:index, :create, :update]
  end

  root 'static#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :recipe
  
  validates :content, presence: true
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @comment = Comment.new
    @recipe = Recipe.find(params[:id])
  end

  def create
    @comment = Comment.new(comment_params)

    if @comment.save
      # @user = User.find(@comment['user_id'])
      render json: @comment, status: 201
    else
      flash[:alert] = @comment.errors.full_messages
      render :new
    end
  end

  def index
    @recipe = Recipe.find(params[:recipe_id])
    @comments = @recipe.comments
    respond_to do |format|
      format.html {render :index }
      format.json {render json:@comments }
    end
  end

  def edit
    @comment = Comment.find(params[:id])
    respond_to do |format|
      format.html {render :edit }
      format.json {render json:@comment }
    end
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:recipe_id])
    @comment = Comment.find(params[:id])
    authorize @comment

    @comment.update(comment_params)
    if @comment.save
      redirect_to recipe_comments_path
    else
      flash[:alert] = @comment.errors.full_messages
      render :edit
    end
  end

  def destroy
    @recipe = Recipe.find(params[:recipe_id])
    @comment = Comment.find(params[:id])
    authorize @comment
    @comment.destroy

    redirect_to recipe_comments_path
  end

  private

  def comment_params
    params.permit(:content, :user_id, :recipe_id, :id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comments.html.erb
<% @recipe.comments.each do |comment| %>

<div class="media">
  <div class="media-body">
    <h4 class="media-heading">
    <%= comment.user.name %> says:
    </h4>
  </div>
  <div id="comment_content">
      <div class="commentos-<%= comment.id %>">
      <%= comment.content %>
      <form id="edit_comment_form">
      <%= text_field_tag :content, comment.content %><br>
      <%= hidden_field_tag :user_id, current_user.id %>
      <%= hidden_field_tag :recipe_id, @recipe.id %>
      <%= hidden_field_tag :id, comment.id %>
      <%= submit_tag "Edit", id: :submit_edit %>
      </form>
    </div>

    <% if current_user.admin? || comment.user_id == current_user.id %>
    <%= link_to "Delete", recipe_comment_path(@recipe, comment.id), id: :delete %>
    <% end %>

    <% if current_user.admin? || current_user.moderator? || comment.user_id == current_user.id %>
    <%= link_to "Edit Your Comments", edit_recipe_comment_path(@recipe, comment), id: :edit %>
    <% end %>
  </div>

</div>
<% end %>

app/views/comments/_edit.html.erb
<%= form_tag(recipe_comment_path, method: :put) %>

  <%= label_tag "Add Your Comment" %><br>
  <%= text_area_tag :content, @comment.content %><br>

  <%= hidden_field_tag :user_id, current_user.id %>
  <%= hidden_field_tag :recipe_id %>

<%= submit_tag %>

app/views/comments/_form.html.erb
<%= form_tag(recipe_comments_path) %>

  <%= label_tag "Add Your Comment" %><br>
  <%= text_area_tag :content %><br>

  <%= hidden_field_tag :user_id, current_user.id %>
  <%= hidden_field_tag :recipe_id, @recipe.id %>

<%= submit_tag "Add Comment" %>

app/views/comments/edit.html.erb
<h2>Edit Comment</h2>
<%= render 'edit' %>

app/views/comments/index.html.erb
<%= render '/recipes/recipe' %>
<%= render 'comments' %>

<div class="media">
  <div class="media-body">
    <h4 class="newUser"></h4>
  </div>
  <div id="newComment">
    <p></p>
  </div>
</div>

<br><br>
<div id="new_comment">
<%= render 'form' %>
</div>

<% content_for :comments do %>
<script>
  $(function() {
    editMethods();
    doEdits();
    deleteMethods();
    createMethods();
  })

  var editMethods = function() {
    $('a#edit').on("click", function(event) {
      event.preventDefault();
      var commentClass = "div." + event['target']['nextSibling']['parentNode']['children']['0']['className'] + " form";
      console.log(commentClass);
      $(commentClass).show();
      // $('commentClass').hide();
    });
  }

  function doEdits() {
    $('#edit_comment_form').on("submit", function(event) {
      event.preventDefault();
      var values = $(this).serialize();
      ajaxEdit(event, values);
      $(this).hide();
    })
  };

  function ajaxEdit(event, values) {
    var comment = event['currentTarget']['0']['value'];
    var user_id = event['currentTarget']['1']['value'];
    var recipe_id = event['currentTarget']['2']['value'];
    var id = event['currentTarget']['3']['value'];
    
    $.ajax ({
        url: "http://localhost:3000/recipes/" + recipe_id + "/comments/" + id + ".json",
        method: 'patch',
        dataType: 'json',
        data: values
      }).done(handleResponse(comment, id));
  };

  function handleResponse(comment, id) {
    $('#edit_comment_form').hide();
    $('.commentos-' + id).text(comment);
    $('#comment_content').show();
  }

  var deleteMethods = function() {
    $('a#delete').on("click", function(event) {
      event.preventDefault();
      var url = event['target']['href'];
      var result = confirm("Are you sure?");
      if(result) {
        $.ajax({
          url: url,
          method: 'delete'
        }).done(deleteResponse(event));
      }
    });
  }

  var deleteResponse = function(event) {
    var comment = event['target']['parentElement'];
    $(comment).text("Comment Deleted");
    console.log(event);
  }

  var createMethods = function() {
    $('div#new_comment form').on("submit", function(event) {
      event.preventDefault();
      var comment = event['currentTarget']['2']['value'];
      var user_id = event['currentTarget']['3']['value'];
      var recipe_id = event['currentTarget']['4']['value'];

      var values = $(this).serialize();

      $.ajax({
        url: "/recipes/" + recipe_id + "/comments/",
        method: 'post',
        data: values,
        dataType: 'json'
      }).done(function(data) {
        $('div#new_comment form').hide();
        $('.newUser').text("<%= current_user.name %>" + " says:");
        $('#newComment').text(data['content']);
      });
    })
  }


</script>
<% end %>

app/views/comments/new.html.erb
<h1>New Comment</h1>
<%= render 'form' %>