config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', :omniauth_callbacks => 'users/omniauth_callbacks'  }
  get '/about' => 'static#about'

  post '/recipe_ingredients' => 'recipeingredients#amount'

  get '/search' => 'recipes#search'
  post '/search' => 'recipes#results'

  resources :ingredients
  resources :recipes do
    resources :comments
    resources :recipe_ingredients, only: [:index, :create, :update]
  end

  root 'static#index'

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients
  
  has_many :comments
  belongs_to :user

  validates :name, presence: true
  validates :name, uniqueness: true
  validates :description, presence: true

  accepts_nested_attributes_for :ingredients

  def self.find_recipe(term)
    recipe = Recipe.find_by(name: term)
  end

  def ingredients_attributes=(ingredients_attributes)
    if ingredients_attributes.values[0]["name"] != ""
      #What a hack... this makes sure that the new ingredient form wasn't blank
      #before building the ingredients. It works around ingredient validation issues.
    ingredients_attributes.each do |i, ingredient_attributes|
        self.ingredients.build(ingredient_attributes)
      end
    end
  end

  def ingredients=(ingredients_array)
    #Did I need to build this custom writer? 
    #It writes to recipe.ingredients from the recipes controller
    ingredients_array.each do |ing|
    if ing != ""
      new_ingredient = Ingredient.find_by_id(ing)
          self.ingredients << new_ingredient unless self.ingredients.include?(ing)
        end
      end
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
    @comment = Comment.new
    @recipe_comments = @recipe.comments
    @recipe_ingredients = @recipe.recipe_ingredients

    respond_to do |format|
      format.html {render :show}
      format.json {render json:@recipe}
    end
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.create(recipe_params)
    @recipe.ingredients = params[:recipe][:ingredient_ids]
    
    if @recipe.save
      redirect_to recipe_recipe_ingredients_path(@recipe)
    else
      message = @recipe.errors.full_messages
      flash[:alert] = message
      render :new
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
    @recipe_ingredients = RecipeIngredient.where(:recipe_id => params[:id])
    authorize @recipe
  end

  def update
    @recipe = Recipe.find(params[:id])
    authorize @recipe
    @recipe.update(recipe_params)

    if @recipe.save
      redirect_to recipe_recipe_ingredients_path(@recipe)
    else
      message = @recipe.errors.full_messages
      flash[:alert] = message
      render :edit
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    authorize @recipe
    @recipe.destroy
    redirect_to recipes_path
  end

  def search
  end

  def results
    term = params["search"]
    recipe = Recipe.find_recipe(term)
    redirect_to recipe_path(recipe)
  end

  private

  def recipe_params
    params.require(:recipe).permit(:user_id, :name, :rating, :description, :ingredient_ids => [], :ingredients_attributes => [:name])
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper

  def recipe_info
    
  end

  def comment_count(recipe)
    count = recipe.comments.size
    pluralize(count, 'comment')
  end

  def rating
    @recipe.rating
  end
end

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>

  <%= f.label :description %><br>
  <%= f.text_area :description %><br>

  <%= f.label "Rating out of 5" %><br>
  <%= f.number_field :rating, min: 1, max: 5 %><br><br>

  <%= f.label "Select Existing Ingredients" %>
  <%= f.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :name, checked: @recipe.try(:ingredient_ids) %><br>

  <h2>Add a new ingredient</h2>
  <%= f.fields_for(:ingredients, Ingredient.new) do |ing_form| %>

  <%= ing_form.label :name %>
  <%= ing_form.text_field :name %><br><br>

  <% end %>

   <%= f.hidden_field :user_id, :value => current_user.id %><br><br>

  <%= f.submit %>
  
<% end %>

app/views/recipes/_recipe.html.erb
<h1><%= @recipe.name %></h1>
<h4>by <%= @recipe.user.name %></h4>
<h5>Rated as <%= @recipe.rating %>/5 </h5>

<p><%= @recipe.description %></p>

<% if current_user.admin? || current_user.moderator? || @recipe.user_id == current_user.id %>
<p><%= link_to "Edit this Recipe", edit_recipe_path(@recipe) %></p>
<% end %>

<h4>Recipe Ingredients</h4>

<div class="table-responsive">
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Ingredient</th>
        <th>Amount <%= link_to "Edit", recipe_recipe_ingredients_path(@recipe), :id => :edit_amount %></th>
      </tr>
    </thead>
    <tbody>
    <% @recipe.ingredients.each do |ingredient|%>
      <tr>
        <td><%= link_to ingredient.name, ingredient_path(ingredient) %></td>
        <td><%= ingredient.recipe_amount(@recipe) %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/recipes/edit.html.erb
<h1>Edit Recipe!</h1>
<%= render 'form' %>

app/views/recipes/index.html.erb
<h1>Your Recipes</h1>

<h4><%= link_to "Add a recipe", new_recipe_path %></h4>

<ul class="list-group">
  <% @recipes.each do |recipe| %>
  <% if recipe.user_id == current_user.id %>
  <li class="list-group-item">
  <h3><%= link_to recipe.name, recipe_path(recipe) %></h3>
    <h4>by <%= recipe.user.name %></h4>
    <h4><%= comment_count(recipe) %></h4>
    <% end %>
  <% end %>
  </li>
  </ul>

<h1>All Recipes</h1>

<ul class="list-group">
  <% @recipes.each do |recipe| %>
  <li class="list-group-item">
    <h3><%= link_to recipe.name, recipe_path(recipe) %></h3>
    <h4>by <%= recipe.user.name %></h4>
    <h4><%= comment_count(recipe) %>
    <% if current_user.admin? %>
    <%= link_to "Delete", recipe_path(recipe), method: :delete %>
    <% end %>
  </li>
<% end %>
</ul>

app/views/recipes/new.html.erb
<h1>New Recipe!</h1>
<%= render 'form' %>

app/views/recipes/search.html.erb
<h1>Search!</h1>

<%= form_tag %>
<%= text_field_tag :search %>
<%= submit_tag "Search" %>

app/views/recipes/show.html.erb
<%= render 'recipe' %>

<br>
<h4>Comments</h4>
<%= link_to "Want to add your own comment?", recipe_comments_path(@recipe.id, @comment), id: :comments %>