config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', :omniauth_callbacks => 'users/omniauth_callbacks'  }
  get '/about' => 'static#about'

  post '/recipe_ingredients' => 'recipeingredients#amount'

  get '/search' => 'recipes#search'
  post '/search' => 'recipes#results'

  resources :ingredients
  resources :recipes do
    resources :comments
    resources :recipe_ingredients, only: [:index, :create, :update]
  end

  root 'static#index'

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :recipe_ingredients
  has_many :recipes, through: :recipe_ingredients

  validates :name, presence: true

  def recipe_amount(recipe)
    q = RecipeIngredient.find_by(:recipe_id => recipe, :ingredient_id => self.id)
    return q.quantity
  end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  def index
    @ingredients = Ingredient.all
    respond_to do |format|
      format.html {render :index}
      format.json {render json:@ingredients}
    end
  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.create(ingredient_params)
    redirect_to ingredients_path
  end

  def show
    @ingredient = Ingredient.find(params[:id])
    respond_to do |format|
      format.html {render :show}
      format.json {render json:@ingredient}
    end
  end

  def edit
    @ingredient = Ingredient.find(params[:id])
    authorize @ingredient
  end

  def update
    @ingredient = Ingredient.find(params[:id])
    @ingredient.update(ingredient_params)
    if @ingredient.save
      redirect_to ingredients_path
    else 
      flash[:alert] = @ingredient.errors.full_messages
      render 'edit'
    end
  end

  def destroy
    @ingredient = Ingredient.find(params[:id])
    authorize @ingredient
    @ingredient.destroy

    redirect_to ingredients_path
  end

  private

  def ingredient_params
    params.require(:ingredient).permit(:id, :name)
  end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/_form.html.erb
<%= form_for @ingredient do |f| %>

<%= f.label :name %>
<%= f.text_field :name %>

<%= f.submit %>

<% end %>

app/views/ingredients/edit.html.erb
<h1>Edit This Ingredient</h1>
<%= render 'form' %>

app/views/ingredients/index.html.erb
<h1 id="header"></h1>

<h4 id="link"></h4>

<div class="list-group">
</ul>

<% content_for :ingredients do %>
<script>
$(function() {
  init()
})

function init() {
  $('#header').html("Ingredients")
  // COOL! ERB works to render HTML in the view through javascript
  $('#link').html('<%= link_to "Add New Ingredient", new_ingredient_path %>');
  $.ajax({
    url: '/ingredients',
    method: 'GET',
    dataType: 'JSON',
    success: function(response) {
      populateLinks(response)
    }
  })
}

function populateLinks(array) {
  var HTML = "<ul>";

  for(var i = 0; i < array.length; i++) {
    var name = array[i].name
    var id = array[i].id
    HTML += "<li class='list-group-item'><a href='/ingredients/" + id + "'>" + name + "</a></li>"
  }
  $('.list-group').html(HTML)
}


</script>
<% end %>

app/views/ingredients/new.html.erb
<h1>New Ingredient</h1>
<%= render 'form' %>

app/views/ingredients/show.html.erb
<h1><%= @ingredient.name %> Ingredient Page</h1>

<p>Ok, cool you have some <%= @ingredient.name %> in your fridge. Check out all the recipes we have and cook something with it!</p>
<p>Click the link to see more about each recipe.</p>

<h3>Recipes Using This Ingredient</h3>

<ul>
<% @ingredient.recipes.each do |recipe| %>
  <li><%= link_to recipe.name, recipe_path(recipe), id: :recipe %></li>
  <h1 id="recipe-<%= recipe.id %>"></h1>
  <p id="recipe-<%= recipe.id %>"></p>
<% end %>
</ul>

<% content_for :ingredient do %>
  <script>
  $(function() {
    linkOverride();
    Recipe();
  });

  var linkOverride = function() {
    $("a#recipe").click(function(event) {
      event.preventDefault();
      loadRecipes(event["target"]["href"]);
    });
  }

  function loadRecipes(target_url) {
    $.getJSON (target_url + ".json", function(result) {
      handleResponse(result);
      hideContent(result['id'])
      })
    };

  var handleResponse = function(result) {
    var recipe = new Recipe(result);
    var hide = ' <a href="#" id="hideMe">Hide this</a>'

    $("h1#recipe-" + recipe.id).html(recipe.name + recipe.readMore);
    $("p#recipe-" + recipe.id).html(recipe.description + recipe.listItems() + hide);
  };

  function Recipe(resultsHash) {
    this.id = resultsHash['id'];
    this.name = resultsHash['name'];
    this.description = resultsHash['description'];
    this.readMore = ' <a href="/recipes/' + recipe.id + '" id="readMore">Read More</a>'
    this.ingredients = resultsHash['ingredients'];
  };

  Recipe.prototype.listItems = function() {
    var ingredientList = '<h5>Other Ingredients in this Recipe</h5><ol>';
    for(var i = 0; i < this.ingredients.length; i++) {
      ingredientList += '<li>' + this.ingredients[i].name + '</li>';
    }
    ingredientList += '</ol>';
    return ingredientList;
  };

  var hideContent = function(id) {
    $('#hideMe').on('click', function(event) {
      event.preventDefault();
      $("h1#recipe-" + id).text("");
      $("p#recipe-" + id).text("");
    });
  }

  </script>
<% end %>