config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', :omniauth_callbacks => 'users/omniauth_callbacks'  }
  get '/about' => 'static#about'

  post '/recipe_ingredients' => 'recipeingredients#amount'

  get '/search' => 'recipes#search'
  post '/search' => 'recipes#results'

  resources :ingredients
  resources :recipes do
    resources :comments
    resources :recipe_ingredients, only: [:index, :create, :update]
  end

  root 'static#index'

end

app/views/layouts/_messages.html.erb
<%= content_tag(:div, flash[:error], :id => "flash_error") if flash[:error] %>
<%= content_tag(:div, flash[:notice], :id => "flash_notice") if flash[:notice] %>
<%= content_tag(:div, flash[:alert], :id => "flash_alert") if flash[:alert] %>

app/views/layouts/_navigation.html.erb
<div class="navbar">
  <div class="container-fluid">
    <%= link_to "Fridge Saver!", root_path, class: "navbar-brand" %>
    <ul class="nav navbar-nav">
    <% if user_signed_in? %>
      <li class="nav navbar-text">
      Hey <%= current_user.name %>!
      </li>
      <li>
      <%= link_to "Ingredients", ingredients_path %>
      </li>
      <li>
      <%= link_to "Your Recipes", recipes_path %>
      </li>
      <li>
      <%= link_to "New Recipe", new_recipe_path %>
      </li>
      <li>
      <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
      </li>
    <% else %>
      <li>
        <%= link_to "Sign Up", new_user_registration_path %>
      </li>
      <li>
        <%= link_to "Sign In", new_user_session_path %>
      </li>
    <% end %>
      <li>
        <a href="/about">About</a>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FridgeSaver</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= yield :ingredient %>
  <%= yield :ingredients %>
  <%= yield :comments %>
  <%= yield :recipes %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="col-sm-12 col-sm-offset-1 col-md-8 col-md-offset-2">

<%= render 'layouts/navigation' %>
<%= render 'layouts/messages' %>

<%= yield %>

</div>
</body>
</html>